[shell]
depends = ["fish"]

[fish.files]
fish = "~/.config/fish"

[shell.files]
bashrc = "~/.bashrc"
shell = "~/.config/shell"
navi = "~/.local/share/navi/cheats"
memo = "~/.local/share/memo"
"starship.toml" = "~/.config/starship.toml"

[vim.files]
LazyVim = { target = "~/.config/LazyVim", type = "symbolic" }

[scripts.files]
scripts = "~/.local/scripts"

[terminal.files]
zellij = "~/.config/zellij"
yazi = "~/.config/yazi"

[git.files]
git = "~/.config/git"
git-cliff = { target = "~/.config/git-cliff", type = "symbolic" }
gitui = "~/.config/gitui"

[templates.files]
Templates = { target = "~/Templates", type = "symbolic" }

[PL.files]
cargo = "~/.cargo"
"pip.conf" = "~/.config/pip/pip.conf"

[monitor.files]
macchina = "~/.config/macchina"
